services:
  - type: web
    name: election-results-socketio
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -k eventlet --timeout 600
    autoDeploy: true
